include ../../Makefile-rules/Makefile

#thanks.png:	$(P2PSP_DOCS)/thanks.png
#		cp $(P2PSP_DOCS)/thanks.png .
#TMPs += thanks.png

#team.svg:	$(P2PSP_DOCS)/papers/white-paper/FIGs/team.pdf
#		echo hola
#TMPs += team.svg
